### ISSUE TITLE
Template: Contributors Page Styling SCSS

### ISSUE THREAD

**Issue by 3daddict** [3daddict/stl-estimator-nodejs#14]
Style the contributers.hbs file to look good.
templates/views/contributors.hbs

- Add github user photos to name.
- Come up with a nice responsive layout 2 Column or 3 Column etc...

**Comment by lindseywild** [comment]
Hey @3daddict! I'm interested in working on this if it's still available.

**Comment by 3daddict** [comment]
You got it @lindseywild !!!

**Comment by lindseywild** [comment]
@3daddict Just to confirm, SCSS files aren't being compiled to CSS now, correct? That needs to be added as well?

**Comment by lindseywild** [comment]
@3daddict I added a quick & dirty way to compile Sass, hope that was ok! If not I can remove it. Otherwise, PR is ready for review 😄

**Comment by 3daddict** [comment]
> @3daddict I added a quick & dirty way to compile Sass, hope that was ok! If not I can remove it. Otherwise, PR is ready for review 😄

@lindseywild ya that's a great way to compile sass. I was just using a vscode extension but that's better. There is an issue outlined to install webpack which was the ultimate goal for compiling. This is a great way until then. Nice work!

**Comment by 3daddict** [comment]
@lindseywild don't forget to add yourself to the contributor page!

**Comment by lindseywild** [comment]
@3daddict Awesome! I didn't know there was a vscode extension to do that... That's cool! Aw shucks 😄 I can add myself in the next few days or so! Thanks, this has been fun to contribute to! I'm a first time Hacktoberfester :)

**Comment by 3daddict** [comment]
Check out [Live Sass Compiler](https://marketplace.visualstudio.com/items?itemName=ritwickdey.live-sass) it's pretty handy. Thanks again for contributing please feel free to suggest features or improvements in the issues area. Glad your liking HacktoberFest your on your way to that t-shirt :-)
