### ISSUE TITLE
Vote for the front-end component CSS library - ALL WELCOME!

### ISSUE THREAD

**Issue by 3daddict** [3daddict/stl-estimator-nodejs#6]
Vote below for the CSS Framework of your choice to be implemented in this project.

To vote click the 👍 and the one with the most thumbs up over the next couple days will get the win!

Last chance to get your votes in before October 1st!

**Comment by 3daddict** [comment]
Vote for [Bootstrap 4](https://getbootstrap.com/)

**Comment by 3daddict** [comment]
Vote for [Materialize](https://materializecss.com/)

**Comment by 3daddict** [comment]
Vote for [Bulma](https://bulma.io/)

**Comment by 3daddict** [comment]
Vote for [Skeleton](http://getskeleton.com/)

**Comment by Snapster02** [comment]
@3daddict I vote Materialize css

**Comment by 3daddict** [comment]
Materialize for the win!
